### ISSUE TITLE
Server response with error

### ISSUE THREAD

**Issue by GramThanos** [tanx8/lolchest#1]
The web app is trying to load my player's info
`http://chestfinder.me/info/EUNE/myplayersname/all`
but the server throws an error

```
{
    "error":{
        "code":"ENOTFOUND",
        "errno":"ENOTFOUND",
        "syscall":"getaddrinfo",
        "hostname":"eune.api.pvp.net",
        "host":"eune.api.pvp.net",
        "port":443
    }
}
```

The error json is also not valid as, Javascript throws an error
```
Uncaught TypeError: error.indexOf is not a function
    at clarifyError (script.js:68)
    at Object.success (script.js:24)
    at i (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at z (jquery.min.js:4)
    at XMLHttpRequest.<anonymous> (jquery.min.js:4)
```

I think the errors are caused by the fact that `eune.api.pvp.net` is not loading.

**Comment by tanx8** [comment]
Hi @GramThanos, thank you for bringing this up. 
It seems that Riot has updated their API endpoints, so the requests are not working anymore. I'm busy with school right now, but I will look into this more when I get the time.

**Comment by tanx8** [comment]
Actually, just updating the endpoint url's did the trick. User searching is working now.

**Comment by GramThanos** [comment]
Thanks! I feel you about the limited free time.
When you have time, check you javascript funtion that handles the errors, as I mentioned it failed to handle the error correctly.
